### PR TITLE
Practicum starter guide

### PR DESCRIPTION
**Pull request by conlin-matt**
I have created this guide to house all of the necessary routines and data files to complete the five practicums presented at the CIRN bootcamp. As a new-user, one of the most challenging aspects of this year's bootcamp was keeping straight where all of these different things were kept; the idea of this starter guide is to eliminate that trouble, making it as easy as possible for new users to successfully complete the practicums. 

Each practicum has its own folder which houses all of the necessary materials. The guide also has a readme which describes how to use it. I invite anyone to try it out and let me know what can be improved, and hopefully this will be useful for new users at future bootcamps!

*Note: The cBathy demo is not currently working because of a few small bugs in the routines for that demo. I will submit a pull request for those changes soon.

### CODE REVIEW

**Comment by conlin-matt** [comment]
@mpalmsten @KateBrodie @RobHolman  With the CIRN Bootcamp coming up next month, I would like to re-propose the addition of this starter guide to the CIRN repos. The idea is that it contains everything needed to complete the CIRN demos, so that new users don't have to struggle with finding inputs/dependencies. All they need to do is clone the CIRN repos and add those and this folder to their path. Let me know if you think this would be a helpful addition, and if so, if it can be improved in any way.

**Comment by eswanson-usgs** [comment]
Closing so that it can be merged into Development without the need for Meg to be reviewer

**Comment by eswanson-usgs** [comment]
Shouldn't have closed. Didn't know code reviews were required for all pull requests in this repo.

**Review by eswanson-usgs — APPROVED** [review]
Discussed changes with Meg and decided it's okay to merge

**Pull request merged**
